## 2. Preprocesado de los datos unidos

In [1]:
import sys
import pandas as pd
import numpy as np
from pathlib import Path

# Paths
processed_input = Path("../data/processed/merged_data.parquet")
preprocessed_output = Path("../data/processed/preprocessed_data.parquet")
preprocessed_output_N = Path("../data/processed/preprocessed_data_N.parquet")

# Add src/ to Python path
sys.path.append(str(Path("../src").resolve()))
from data.downcast import downcast_numeric_columns


# Display options for large datasets (we have 3.4M rows!!)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 10)

In [2]:
df = pd.read_parquet(processed_input, engine="fastparquet")  # same engine as saved (fastparquet)
print("Forma original:", df.shape)
df.head()

Forma original: (3476825, 81)

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,Bwd Pkt Len Min,Bwd Pkt Len Mean,Bwd Pkt Len Std,Flow Byts/s,Flow Pkts/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Tot,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Tot,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Len,Bwd Header Len,Fwd Pkts/s,Bwd Pkts/s,Pkt Len Min,Pkt Len Max,Pkt Len Mean,Pkt Len Std,Pkt Len Var,FIN Flag Cnt,SYN Flag Cnt,RST Flag Cnt,PSH Flag Cnt,ACK Flag Cnt,URG Flag Cnt,CWE Flag Count,ECE Flag Cnt,Down/Up Ratio,Pkt Size Avg,Fwd Seg Size Avg,Bwd Seg Size Avg,Fwd Byts/b Avg,Fwd Pkts/b Avg,Fwd Blk Rate Avg,Bwd Byts/b Avg,Bwd Pkts/b Avg,Bwd Blk Rate Avg,Subflow Fwd Pkts,Subflow Fwd Byts,Subflow Bwd Pkts,Subflow Bwd Byts,Init Fwd Win Byts,Init Bwd Win Byts,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,source_file
0,0,0,2018-02-14 08:31:01,112641719,3,0,0,0,0,0,0.000000,0.000000,0,0,0.000000,0.000000,0.000000,0.026633,5.632086e+07,139.300036,56320958,56320761,112641719,5.632086e+07,139.300036,56320958,56320761,0,0.000000,0.000000,0,0,0,0,0,0,0,0,0.026633,0.000000,0,0,0.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.00,0.000000,0.000000,0,0,0,0,0,0,3,0,0,0,-1,-1,0,0,0.0,0.0,0,0,56320859.5,139.300036,56320958,56320761,Benign,Wednesday-14-02-2018_TrafficForML_CICFlowMeter
1,0,0,2018-02-14 08:33:50,112641466,3,0,0,0,0,0,0.000000,0.000000,0,0,0.000000,0.000000,0.000000,0.026633,5.632073e+07,114.551299,56320814,56320652,112641466,5.632073e+07,114.551299,56320814,56320652,0,0.000000,0.000000,0,0,0,0,0,0,0,0,0.026633,0.000000,0,0,0.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.00,0.000000,0.000000,0,0,0,0,0,0,3,0,0,0,-1,-1,0,0,0.0,0.0,0,0,56320733.0,114.551299,56320814,56320652,Benign,Wednesday-14-02-2018_TrafficForML_CICFlowMeter
2,0,0,2018-02-14 08:36:39,112638623,3,0,0,0,0,0,0.000000,0.000000,0,0,0.000000,0.000000,0.000000,0.026634,5.631931e+07,301.934596,56319525,56319098,112638623,5.631931e+07,301.934596,56319525,56319098,0,0.000000,0.000000,0,0,0,0,0,0,0,0,0.026634,0.000000,0,0,0.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.00,0.000000,0.000000,0,0,0,0,0,0,3,0,0,0,-1,-1,0,0,0.0,0.0,0,0,56319311.5,301.934596,56319525,56319098,Benign,Wednesday-14-02-2018_TrafficForML_CICFlowMeter
3,22,6,2018-02-14 08:40:13,6453966,15,10,1239,2273,744,0,82.600000,196.741237,976,0,227.300000,371.677892,544.161528,3.873587,2.689152e+05,247443.778966,673900,22,6453966,4.609976e+05,123109.423588,673900,229740,5637902,626433.555556,455082.214224,1167293,554,0,0,0,0,488,328,2.324152,1.549435,0,976,135.076923,277.834760,77192.153846,0,0,0,1,0,0,0,0,0,140.48,82.600000,227.300000,0,0,0,0,0,0,15,1239,10,2273,65535,233,6,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign,Wednesday-14-02-2018_TrafficForML_CICFlowMeter
4,22,6,2018-02-14 08:40:23,8804066,14,11,1143,2209,744,0,81.642857,203.745545,976,0,200.818182,362.249864,380.733175,2.839597,3.668361e+05,511356.609733,1928102,21,8804066,6.772358e+05,532416.970959,1928102,246924,7715481,771548.100000,755543.082717,2174893,90,0,0,0,0,456,360,1.590174,1.249423,0,976,128.923077,279.763032,78267.353846,0,0,0,1,0,0,0,0,0,134.08,81.642857,200.818182,0,0,0,0,0,0,14,1143,11,2209,5808,233,6,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign,Wednesday-14-02-2018_TrafficForML_CICFlowMeter

#### 1) Tratamiento de NAs e infinitos

En este caso todos se concentran en el Flow de Byts por tanto podríamos poner un valor de 0.0 como tinen algunos o directamente eliminar las filas relacionadas.

In [3]:
df.isna().sum()[df.isna().sum()!=0]

Flow Byts/s    9032
dtype: int64

Como podemos ver otra vez estos pueden estar relacionados a algunos ataques pero no es común, por tanto podemos suponer que es algun error de trafico normal. Y la proporción de los ataques que sufren de esto es muy baja comparada con el total.

In [4]:
df[df.isna().any(axis=1)]['Label'].value_counts()

Label
Benign            8597
Infilteration      429
FTP-BruteForce       6
Name: count, dtype: int64

Considero que poner un valor de 0.0 alteraría la información y por tanto voy a decidirme por borrar dichas filas.

Ahora necesito comprobar valores infinitos:

In [5]:
numeric_df = df.select_dtypes(include=[np.number])
inf_counts = np.isinf(numeric_df).sum()
inf_counts[inf_counts > 0]

Flow Byts/s     5738
Flow Pkts/s    14770
dtype: int64

Ahora cambio los valores infinitos por NAs para eliminarlos con los NAs que habíamos localizado antes:

In [6]:
df = df.replace([np.inf, -np.inf], np.nan)
df=df.dropna()
df.isna().sum()

Dst Port         0
Protocol         0
Timestamp        0
Flow Duration    0
Tot Fwd Pkts     0
                ..
Idle Std         0
Idle Max         0
Idle Min         0
Label            0
source_file      0
Length: 81, dtype: int64

Compruebo que efectivamente también se han eliminado los valores infinitos, valor False quiere decir que no hay infinitos:

In [7]:
np.isinf(df.select_dtypes(include=[np.number])).any().any()

np.False_

#### 2) Eliminación de variables con varianza = 0

Para empezar vamos a eliminar las columnas de varianza 0, no nos aportan información a nuestro análisis si su varianza es exactamente 0, significa que no cambian:

In [8]:
zero_var_cols = df.select_dtypes(include=['number']).var()[lambda x: x == 0]
zero_var_cols

Bwd PSH Flags       0.0
Bwd URG Flags       0.0
Fwd Byts/b Avg      0.0
Fwd Pkts/b Avg      0.0
Fwd Blk Rate Avg    0.0
Bwd Byts/b Avg      0.0
Bwd Pkts/b Avg      0.0
Bwd Blk Rate Avg    0.0
dtype: float64

In [9]:
df = df.drop(columns=zero_var_cols.index)

#### 3) Tratamiento de duplicados

In [10]:
# Total number of duplicate rows
num_duplicates = df.duplicated().sum()
print(f"Total de filas duplicadas (todas las columnas iguales): {num_duplicates}")

Total de filas duplicadas (todas las columnas iguales): 245669

In [11]:
# Show first 5 duplicate rows
df[df.duplicated()].head()

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,Bwd Pkt Len Min,Bwd Pkt Len Mean,Bwd Pkt Len Std,Flow Byts/s,Flow Pkts/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Tot,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Tot,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Fwd URG Flags,Fwd Header Len,Bwd Header Len,Fwd Pkts/s,Bwd Pkts/s,Pkt Len Min,Pkt Len Max,Pkt Len Mean,Pkt Len Std,Pkt Len Var,FIN Flag Cnt,SYN Flag Cnt,RST Flag Cnt,PSH Flag Cnt,ACK Flag Cnt,URG Flag Cnt,CWE Flag Count,ECE Flag Cnt,Down/Up Ratio,Pkt Size Avg,Fwd Seg Size Avg,Bwd Seg Size Avg,Subflow Fwd Pkts,Subflow Fwd Byts,Subflow Bwd Pkts,Subflow Bwd Byts,Init Fwd Win Byts,Init Bwd Win Byts,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,source_file
96,21,6,2018-02-14 10:33:26,3,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,666666.666667,3.0,0.0,3,3,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,40,20,333333.333333,333333.333333,0,0,0.0,0.0,0.0,0,0,0,1,0,0,0,0,1,0.0,0.0,0.0,1,0,1,0,26883,0,0,40,0.0,0.0,0,0,0.0,0.0,0,0,FTP-BruteForce,Wednesday-14-02-2018_TrafficForML_CICFlowMeter
98,21,6,2018-02-14 10:33:26,2,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,1000000.000000,2.0,0.0,2,2,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,40,20,500000.000000,500000.000000,0,0,0.0,0.0,0.0,0,0,0,1,0,0,0,0,1,0.0,0.0,0.0,1,0,1,0,26883,0,0,40,0.0,0.0,0,0,0.0,0.0,0,0,FTP-BruteForce,Wednesday-14-02-2018_TrafficForML_CICFlowMeter
99,21,6,2018-02-14 10:33:26,2,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,1000000.000000,2.0,0.0,2,2,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,40,20,500000.000000,500000.000000,0,0,0.0,0.0,0.0,0,0,0,1,0,0,0,0,1,0.0,0.0,0.0,1,0,1,0,26883,0,0,40,0.0,0.0,0,0,0.0,0.0,0,0,FTP-BruteForce,Wednesday-14-02-2018_TrafficForML_CICFlowMeter
100,21,6,2018-02-14 10:33:26,2,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,1000000.000000,2.0,0.0,2,2,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,40,20,500000.000000,500000.000000,0,0,0.0,0.0,0.0,0,0,0,1,0,0,0,0,1,0.0,0.0,0.0,1,0,1,0,26883,0,0,40,0.0,0.0,0,0,0.0,0.0,0,0,FTP-BruteForce,Wednesday-14-02-2018_TrafficForML_CICFlowMeter
101,21,6,2018-02-14 10:33:26,2,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,1000000.000000,2.0,0.0,2,2,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,40,20,500000.000000,500000.000000,0,0,0.0,0.0,0.0,0,0,0,1,0,0,0,0,1,0.0,0.0,0.0,1,0,1,0,26883,0,0,40,0.0,0.0,0,0,0.0,0.0,0,0,FTP-BruteForce,Wednesday-14-02-2018_TrafficForML_CICFlowMeter

Aunque haya muchos duplicados la mayoría de ellos corresponden a ataques de bruteforce por lo cual eliminarlos nos afectaría negativamente a la posterior clasificación. Aquí podemos ver calculadas las proporciones de duplicados en tanto porciento.

In [12]:
dup_counts = df[df.duplicated()]['Label'].value_counts()
total_counts = df['Label'].value_counts()
(dup_counts / total_counts * 100).fillna(0).sort_values(ascending=False)

Label
FTP-BruteForce           79.650796
SSH-Bruteforce           37.457953
DoS attacks-Slowloris     6.414923
DDOS attack-HOIC          2.558410
Benign                    0.136182
DoS attacks-GoldenEye     0.127686
Infilteration             0.024891
DDOS attack-LOIC-UDP      0.000000
Name: count, dtype: float64

Como solución a este problema de duplicados hemos decidido crear una nueva variable llamada "repetition_count" que represente las veces que se repite dicha fila. Y elimino ya los duplicados.

In [13]:
original_cols = df.columns.tolist()
df['repetition_count'] = df.groupby(original_cols).transform('size')
df=df.drop_duplicates(subset=original_cols)

Compruebo que efectivamente ya no hay duplicados:

In [14]:
df.duplicated().sum()

np.int64(0)

#### 5) Categorización de los puertos de destino

Dejo esta variable porque nos puede ayudar a discriminar pero hay que tomarla con cuidado porque puede estar sesgada al experimento.

In [15]:
df['Dst Port Cat'] = "unknown"

df.loc[df['Dst Port'].isin([80, 443]), 'Dst Port Cat'] = "web"
df.loc[df['Dst Port'] == 53, 'Dst Port Cat'] = "dfs"
df.loc[df['Dst Port'] == 22, 'Dst Port Cat'] = "ssh"
df.loc[df['Dst Port'] == 21, 'Dst Port Cat'] = "ftp"
df.loc[df['Dst Port'] == 3389, 'Dst Port Cat'] = "rdp"

df.loc[(df['Dst Port'] < 1024) & 
       (~df['Dst Port'].isin([21,22,53,80,443,3389])), 'Dst Port Cat'] = "well_known_other"

df.loc[(df['Dst Port'] >= 1024) & (df['Dst Port'] < 49152), 'Dst Port Cat'] = "registered"

df.loc[df['Dst Port'] >= 49152, 'Dst Port Cat'] = "ephemeral"

Compruebo que todos los flujos esten categorizados bien.

In [16]:
df['Dst Port Cat'].value_counts()

Dst Port Cat
web                 1350228
dfs                  638579
ephemeral            609489
registered           286432
well_known_other     171623
ssh                  120549
ftp                   39486
Name: count, dtype: int64

Ahora compruebo la relación con los ataques, vemos que está muy relacionada la variable Dst Port Cat con los ataques y eso significa que pueden ser muy útile para la clasificación, pero debemos estar atentos a posibles sesgos de la simulación para no caer en un sobreajuste y probre generalización de los modelos que ajustemos.

In [17]:
pd.crosstab(df['Dst Port Cat'], df['Label'])

Label,Benign,DDOS attack-HOIC,DDOS attack-LOIC-UDP,DoS attacks-GoldenEye,DoS attacks-Slowloris,FTP-BruteForce,Infilteration,SSH-Bruteforce
Dst Port Cat,,,,,,,,
dfs,612795,0,0,0,0,0,25784,0
ephemeral,598748,0,0,0,0,0,10741,0
ftp,104,0,0,0,0,39346,29,7
registered,257056,0,0,0,0,0,29376,0
ssh,2476,0,0,0,0,0,758,117315
web,613074,668461,1730,41455,10285,0,15223,0
well_known_other,161154,0,0,0,0,0,10469,0

#### 6) Eliminación de variables no relevantes

Ahora eliminaremos variables que por la construcción del dataset no son relevantes a nuestro analisis ya que están condicionadas por su generación, lo cuál puede generar artefactos en nuestro analisis (información sesgada a la forma de generación de los datos). Estas variables son Flow ID, Source IP, Destination IP, Source Port, Destination Port y Timestamp. En otros trabajos similares se las elimina por los mismos motivos. Aprovecho también a eliminar la variable source_file ya que nos es irrelevante también.

In [18]:
cols_to_drop = [
    'Src IP',
    'Dst IP',
    'Flow ID',
    'Timestamp',
    'Src Port',
    'Dst Port',
    'source_file'
]

df = df.drop(columns=cols_to_drop, errors='ignore')

Compruebo que efectivamente ya no esten esas variables:

In [19]:
print(df.columns.tolist())
print(df.shape)

['Protocol', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Fwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Subflow Fwd Pkts', 'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts', 'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label', 'repetition_count', 'Dst Port Cat']
(3216386, 72)

Comprobación de duplicados ahora que he quitado las variables y he hecho los agrupados. Ahora cada fila es un flujo distinto pero los hay que son completamente iguales y los hay que son completamente iguales y con diferente clasificación.

In [20]:
label_col = "Label"

# --- 1. NEW DUPLICATES (ALL FEATURES, included Label) ---
num_duplicates = df.duplicated().sum()

# --- 2. CONFLICTS (ALL FEATURES except Label) ---
feature_cols = df.columns.drop(label_col)
# rows that belong to a feature-group with more than one label
conflict_mask = df.groupby(list(feature_cols))[label_col].transform("nunique").gt(1)
n_conflict_rows = conflict_mask.sum()

# --- OUTPUT ---
print("Exact duplicate rows (including Label):", num_duplicates)
print("Conflict rows (features identical but different labels):", n_conflict_rows)

Exact duplicate rows (including Label): 1033861
Conflict rows (features identical but different labels): 99305

In [21]:
df[df.duplicated()].head()

,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,Bwd Pkt Len Min,Bwd Pkt Len Mean,Bwd Pkt Len Std,Flow Byts/s,Flow Pkts/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Tot,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Tot,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Fwd URG Flags,Fwd Header Len,Bwd Header Len,Fwd Pkts/s,Bwd Pkts/s,Pkt Len Min,Pkt Len Max,Pkt Len Mean,Pkt Len Std,Pkt Len Var,FIN Flag Cnt,SYN Flag Cnt,RST Flag Cnt,PSH Flag Cnt,ACK Flag Cnt,URG Flag Cnt,CWE Flag Count,ECE Flag Cnt,Down/Up Ratio,Pkt Size Avg,Fwd Seg Size Avg,Bwd Seg Size Avg,Subflow Fwd Pkts,Subflow Fwd Byts,Subflow Bwd Pkts,Subflow Bwd Byts,Init Fwd Win Byts,Init Bwd Win Byts,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,repetition_count,Dst Port Cat
115,6,4,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,500000.000000,4.0,0.0,4,4,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,40,20,250000.000000,250000.000000,0,0,0.0,0.0,0.0,0,0,0,1,0,0,0,0,1,0.0,0.0,0.0,1,0,1,0,26883,0,0,40,0.0,0.0,0,0,0.0,0.0,0,0,FTP-BruteForce,1,ftp
144,6,18,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,111111.111111,18.0,0.0,18,18,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,40,20,55555.555556,55555.555556,0,0,0.0,0.0,0.0,0,0,0,1,0,0,0,0,1,0.0,0.0,0.0,1,0,1,0,26883,0,0,40,0.0,0.0,0,0,0.0,0.0,0,0,FTP-BruteForce,2,ftp
185,6,19,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,105263.157895,19.0,0.0,19,19,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,40,20,52631.578947,52631.578947,0,0,0.0,0.0,0.0,0,0,0,1,0,0,0,0,1,0.0,0.0,0.0,1,0,1,0,26883,0,0,40,0.0,0.0,0,0,0.0,0.0,0,0,FTP-BruteForce,2,ftp
207,6,4,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,500000.000000,4.0,0.0,4,4,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,40,20,250000.000000,250000.000000,0,0,0.0,0.0,0.0,0,0,0,1,0,0,0,0,1,0.0,0.0,0.0,1,0,1,0,26883,0,0,40,0.0,0.0,0,0,0.0,0.0,0,0,FTP-BruteForce,1,ftp
215,6,18,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,111111.111111,18.0,0.0,18,18,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,40,20,55555.555556,55555.555556,0,0,0.0,0.0,0.0,0,0,0,1,0,0,0,0,1,0.0,0.0,0.0,1,0,1,0,26883,0,0,40,0.0,0.0,0,0,0.0,0.0,0,0,FTP-BruteForce,2,ftp

#### 7) Tipos de datos

Ahora debo ajustar los tipos de datos a sus correspondientes.

In [22]:
df.dtypes.value_counts()

int64      46
float64    24
object      1
str         1
Name: count, dtype: int64

In [23]:
print(df.dtypes)

Protocol             int64
Flow Duration        int64
Tot Fwd Pkts         int64
Tot Bwd Pkts         int64
TotLen Fwd Pkts      int64
                     ...
Idle Max             int64
Idle Min             int64
Label               object
repetition_count     int64
Dst Port Cat           str
Length: 72, dtype: object

Cambiamos a category los que se pueden categorizar, protocolos, etiquetas y csv de origen.

In [24]:
df['Protocol'] = df['Protocol'].astype('category')
df['Label'] = df['Label'].astype('category')
df['Dst Port Cat'] = df['Dst Port Cat'].astype('category')
print(df.dtypes)

Protocol            category
Flow Duration          int64
Tot Fwd Pkts           int64
Tot Bwd Pkts           int64
TotLen Fwd Pkts        int64
                      ...
Idle Max               int64
Idle Min               int64
Label               category
repetition_count       int64
Dst Port Cat        category
Length: 72, dtype: object

Finalmente un punto importante será la conversión del tipo de datos pasar de 64 a 32 porque no nos hace falta tanto, pero primero comprobamos los casos en los que no se puede hacer este downcast. Una vez lo hemos verificado procedemos a hacer downcast en las posibles esto va a conllevar un mejor rendimiento general del dataset.

In [25]:
downcast_numeric_columns(df)

Columnas enteras que NO se pueden downcast:
['Flow Duration', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Max', 'Fwd IAT Min', 'Idle Max', 'Idle Min']

Columnas float que NO se pueden downcast:
[]

Downcasting completado.

In [26]:
df.dtypes.value_counts()

uint32      35
float32     24
int64        8
int32        2
category     1
category     1
category     1
Name: count, dtype: int64

#### 8) Extras

Vemos que todo va acorde con la teoría de la red, los protocolos.

In [27]:
df['Protocol'].value_counts()

Protocol
6     2511284
17     667447
0       37655
Name: count, dtype: int64

#### Volvemos a guardar el dataset preprocesado

In [28]:
print("Forma después del preprocesado:", df.shape)

Forma después del preprocesado: (3216386, 72)

In [29]:
df.to_parquet(preprocessed_output, engine="pyarrow", index=False)

Como solución a este problema de duplicados hemos decidido crear una nueva variable llamada "repetition_flow" que represente las veces que se repite dicha las caracteristicas de un flujo en otros. Y elimino ya los duplicados.

In [30]:
original_cols = df.columns.tolist()
df['repetition_flow'] = df.groupby(original_cols).transform('size')
df=df.drop_duplicates(subset=original_cols)

Compruebo que efectivamente ya no hay duplicados:

In [33]:
df.duplicated().sum()

np.int64(135)

In [32]:
print("Forma después del tratamiento de flujos iguales:", df.shape)

Forma después del tratamiento de flujos iguales: (2155421, 73)

In [33]:
df.to_parquet(preprocessed_output_N, engine="pyarrow", index=False)